name: passengerapp
description: "Passenger App Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  country_picker: ^2.0.27

  http: ^1.5.0

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Firebase
  firebase_core: 4.13.0
  firebase_auth: ^6.1.2
  firebase_database: ^12.1.0
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.0.0
  cloud_functions: 6.3.6

  # Maps & Media
  google_maps_flutter: ^2.13.1
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  share_plus: ^12.0.2
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/south_sudan_flag.png
    - assets/images/vehicles/alpha_boda.webp
    - assets/images/vehicles/alpha_boda_top.webp
    - assets/images/vehicles/alpha_comfort.webp
    - assets/images/vehicles/alpha_corporate.webp
    - assets/images/vehicles/alpha_driver_top.webp
    - assets/images/vehicles/alpha_ev.webp
    - assets/images/vehicles/alpha_premium.webp
    - assets/images/vehicles/alpha_rickshaw.webp
    - assets/images/vehicles/alpha_rickshaw_top.webp
    - assets/images/vehicles/alpha_standard.webp

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#39FF14"
  adaptive_icon_foreground: assets/images/logo.png
  adaptive_icon_foreground_inset: 0
