// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJrHQRxEjgRMwdpiLD8sbqyoAVxUgLQ0',
    appId: '1:1089638546298:android:4f467d316283f9ce47b4c3',
    messagingSenderId: '1089638546298',
    projectId: 'taxi-b58df',
    databaseURL: 'https://taxi-b58df-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-b58df.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5-vNpfNRhHqabPFpCUCTBnYADC6nVSzI',
    appId: '1:486103357366:ios:931a31f088a57d5f7f1317',
    messagingSenderId: '486103357366',
    projectId: 'alpha-ride-29708',
    storageBucket: 'alpha-ride-29708.firebasestorage.app',
    iosBundleId: 'com.example.passengerApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQfe36JwUXD4-Xq9_ky2IQD3mLwOORUhk',
    appId: '1:486103357366:web:98c3bd6fd18719067f1317',
    messagingSenderId: '486103357366',
    projectId: 'alpha-ride-29708',
    authDomain: 'alpha-ride-29708.firebaseapp.com',
    storageBucket: 'alpha-ride-29708.firebasestorage.app',
    measurementId: 'G-S0KV53726R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5-vNpfNRhHqabPFpCUCTBnYADC6nVSzI',
    appId: '1:486103357366:ios:931a31f088a57d5f7f1317',
    messagingSenderId: '486103357366',
    projectId: 'alpha-ride-29708',
    storageBucket: 'alpha-ride-29708.firebasestorage.app',
    iosBundleId: 'com.example.passengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQfe36JwUXD4-Xq9_ky2IQD3mLwOORUhk',
    appId: '1:486103357366:web:6d53a8689faacfee7f1317',
    messagingSenderId: '486103357366',
    projectId: 'alpha-ride-29708',
    authDomain: 'alpha-ride-29708.firebaseapp.com',
    storageBucket: 'alpha-ride-29708.firebasestorage.app',
    measurementId: 'G-5BC926PFRV',
  );
}
